{
  imports = [
    ./theme.nix
    ./languages.nix
    ./debugger.nix
    ./cmp.nix
    ./editing.nix
    ./git.nix
    ./ui.nix
    ./lsp.nix
    ./telescope.nix
    ./terminal.nix
    ./utility.nix
    ./file-tree.nix
    ./buffer-line.nix
    ./status-line.nix
    ./direnv.nix
  ];
}
